# Generated by Django 5.0 on 2024-12-19 16:51

import django.db.models.deletion
import django.utils.timezone
import gastos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categoria')),
                ('icon', models.FileField(upload_to='archivos/', validators=[gastos.models.validar_imagen_o_svg], verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Presupuesto')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('initial_budget', models.FloatField(verbose_name='Presupuesto Inicial')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=150, verbose_name='Nombre del Gasto')),
                ('amount', models.FloatField(verbose_name='Cantidad en Pesos')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.categoria', verbose_name='Categoria')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['amount', 'expense_name'],
            },
        ),
    ]
