# Generated by Django 5.0 on 2024-12-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
